import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import {useState, useEffect} from 'react'
import {BsSearch } from 'react-icons/bs';
import Weather from '../components/Weather';
import Spinner from '../components/Spinner';

export default function Home() {
  
  const [city,setCity] = useState('manhattan');
  const [weather, setWeather] = useState({})
  const [ loading, setLoading ] = useState(false)

  const que=[
    { 
      name: 'London',
    },
    {
      name:'Manhattan',
    },
    {
      name:'Tokyo',
    },
    {
      name:'Paris',
    }
  ]


  const url=`https://api.openweathermap.org/data/2.5/weather?q=${city}&units=imperial&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`
  
  useEffect(() => {
    const fetchWeather = async () => {
      
      await axios.get(url).then((response) => {
        setWeather(response.data)
        
      })
      setCity('')
      setLoading(false)
    }
    fetchWeather();
  },[city])

  if(loading) {
    return <Spinner />
  } else {
    return (
      <div className="">
        <Head>
          <title>Weather-App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      {/* OverLay*/}
      <div className='absolute top-0 left-0 right-0 bottom-0 bg-black/50 z-[1]'/>
      {/* background-image */}
        <Image 
        src="https://images.unsplash.com/photo-1507781630884-dfbeefd94236?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1474&q=80" 
        layout='fill'
        className='object-cover ' />
  
        {/*Search */}
        <div className="flex ">
          <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
            <form 
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'>
              <div>
                <input 
                onChange={(e) => setCity(e.target.value)}
                className='bg-transparent border-none text-white focus:outline-none text-2xl placeholder:text-slate-500' type='text' placeholder='Search for a City'/>
              </div>
              <button className='' onClick={(e) => setCity(e.target.value)} ><BsSearch size={20}/></button>
            </form>
        </div>
        </div>
        <div className="flex justify-evenly max-w-[500px] w-full m-auto ">
        {que.map((q) => (
                  <h1 className=" top-[10px] relative justify-around text-white text-lg font-medium hover:scale-110 z-20 cursor-pointer" key={q.name} 
                  onClick={ () => setCity(q.name)}>
                      {q.name}
                  </h1>
              ))}
        </div>
        
        {/*Weather*/}
        {weather.main && <Weather data={weather} />}
      </div>
    )


  }

  
}
